#!/usr/bin/env bash
mkdir -p ~/.config/nvim/plugin
mkdir -p ~/.config/nvim/after/plugin
mkdir -p ~/.config/nvim/lua

# link everything
for f in `find -E . -regex "(.*\.vim$|.*\.lua$)"`; do
  rm -rf ~/.config/nvim/$f
  ln -s ~/dotfiles/neovim/$f ~/.config/nvim/$f
  echo $f
done
